#:kivy 2.0.0

<MainScreen>:

    FloatLayout:
        pos: 0, 0
        size: root.width, root.height

        GridLayout:
            cols: 1
            pos_hint: {'x': 0.375,'y': 0.025}
            size_hint: 0.25 , 0.1

            Button:
                text: "Run"
                font_size: 32
                background_color: (100, 0, 0, 0.5)
                on_press: root.RunPress()
                on_release: root.RunRelease()